### ISSUE TITLE
Rethink rule definitions

### ISSUE THREAD

**Issue by chriscz** [chriscz/pySorter#31]
This issue is for discussing ways to make the rule definitions more flexible and accessible to a wider audience of non python programmers.

- [ ] Think of ways to split the existing rules into sensible categories
- [ ]  Add support for defining sorting rules using YAML.

**Comment by kontravariant** [comment]
Following up on my reddit comment on this! Looking forward to helping if I can.

I like the proposition of YAML. Rules could be named, and priority can be given. They could be grouped ala [Ansible Groups](http://docs.ansible.com/ansible/latest/intro_inventory.html#hosts-and-groups) 

I'm thinking something like this (from the README):
```yaml
    ---
    pdf:
        - pattern = '.*\.pdf$'
        - dest = 'documents/pdf/'
        - priority = 0
```
(the pattern, dest and priority can either be explicit, or implicitly defined by their order, or both)

In this way, rules don't have to be manually reorganized to reassign priority. As well, this could be extended to allow for grouping definitions (possibly in the same file) and assigning priorities there (with a decision needing to be made on which priority takes precedent).

**Comment by chriscz** [comment]
Thanks for your interest Tyler!

I like the priority idea and can see its usefulness, but I want to think more about the 
overall structure of this before tackling it. I would especially like to see
examples where existing functionality is possible.

Also, your yaml example is valid, but entries such as `a = 1` are seen as strings, 
I believe you intended it to be something like
```yaml
 pdf:
    pattern : '.*\.pdf$'
    dest : 'documents/pdf/'
    priority : 0
```
Some questions that would drive the design (please tell me if you have any others)
1. Would importing definitions from other files be useful to power users or does it complicate matters?
2. How would we reference standard rule definitions such the recent *mimetypes* pattern support?
3. Support should remain for skipping (files and directory traversals)

### Example
Below is a draft of some "nice-to-have" / usable styles for your 
suggestion of groups.

```yaml
---
# non-rule configuration
config:
  # all non-absolute paths these are relative to this file
  - include: 
    - name: foo
      path: foo.yml

      # name inferred as bar
    - path: bar.yml

  # include rules defined somewhere in python
  - pyinclude:
    # this variable doesn't exist yet, but will (if) this gets implemented
    - pysorter.rules.mimetypes
  
  - order:
    # x and y indicate groups
    - 'bar:xxx'

    # in this file
    - :documents

    # include all groups
    - 'foo:*'

    # all (remaining) groups from this file
    - ':*'
    
    # the python included rules
    - pysorter_rules_mimetypes

# rule definitions
documents:
  # a default priority for this group (when compared to other groups)
  # this could lead to confusion, hence the g prefix
  gpri : 0
  # (optional) prefix for all consequent destination. 
  # This is literally prepended, so no implicit slash will be added
  dst-prefix: 'foo/'
  # a default destination inherited by all 
  dst : 'documents/' 
  rules:
      - pat: '(?P<year>\d{4})\.pdf$'
        dst: 'documents/pdfs_{year}.pdf'

      # long form
      - pat: '\.pdf$'
        dst: 'documents/pdfs/'
        pri: -10 # optional priority (higher takes precedence)

      # alternative shortform (also excluding quotes, which is apparently legal)
      # here only the pattern is given and the destination is inferred from dst.
      # would only be legal when group dst is defined
      - \.docx$

      # another shortform as a list
      - ['\.xlsx$', 'documents/excel/']
      
      # OR
      - - '\.xlsx$'
        - 'documents/excel/'

      # Skipping actions (skip these filetypes instead of moving)
      # for these the dst would not matter
      - pat: \.doc$
        action: skip
```
I won't have time to implement this in these next two month, 
so help wil be appreciated.

Let me know what you think!

**Comment by kontravariant** [comment]
Glad to help! Looking forward to working on this. 

> 1. Would importing definitions from other files be useful to power users or does it complicate matters?

I would suggest modeling after the Ansible Inventory system. In the long term, allowing for rules to be defined in yaml files, they can then be referenced by their inventory file name (i.e. inv1.ruleX, where ruleX is a rule in inv1.yaml) and put into groups, or custom sets of definitions on the fly. 

> 2. How would we reference standard rule definitions such the recent mimetypes pattern support?

I assume you are referring to [this commit](https://github.com/chriscz/pysorter/pull/26/commits/781498747209d5b11c264cb1c05bc7568a393ec2)? I'm not quite sure I know what you are suggesting, but I would think standard rule definitions can either be left alone, or overridden if a rule conflicts.

> 3. Support should remain for skipping (files and directory traversals)

I like your suggestion for skipping
```yaml
---
  - pat: \.doc$
    action: skip
```

However I think it may be better to reserve a keyword "skips" for this purpose:
i.e.
```yaml
# rule definitions
documents:
  gpri : 0
  dst-prefix: 'foo/'
  dst : 'documents/' 
  rules:
        # rules here...
  skips:
      - ['\.docx$', '\.xlsx$']
```

I will start familiarizing myself with the codebase and design patterns!
